export const PRODUCTOS = [
  // Comidaas
  {
    id: 'a1',
    nombre: 'Tacos al Pastor (3 uds)',
    precio: 4.50,
    categoria: 'alimentos',
    imagen: 'https://res.cloudinary.com/dh81vvqax/image/upload/v1789061149/pastor_sadvop.avif',
  },
  {
    id: 'a2',
    nombre: 'Tacos de Asada (3 uds)',
    precio: 5.00,
    categoria: 'alimentos',
    imagen: 'https://res.cloudinary.com/dh81vvqax/image/upload/v1789061546/Tacos_de_Asada_mvwxyy.jpg',
  },
  {
    id: 'a3',
    nombre: 'Quesadilla de Queso',
    precio: 3.50,
    categoria: 'alimentos',
    imagen: 'https://res.cloudinary.com/dh81vvqax/image/upload/v1789061545/Quesadilla_de_Queso_pymjb4.webp',
  },
  {
    id: 'a4',
    nombre: 'Burrito de Pollo',
    precio: 6.25,
    categoria: 'alimentos',
    imagen: 'https://res.cloudinary.com/dh81vvqax/image/upload/v1789061542/Burrito_de_Pollo_ci9xy6.jpg',
  },
  {
    id: 'a5',
    nombre: 'Gringa de Suadero',
    precio: 4.75,
    categoria: 'alimentos',
    imagen: 'https://res.cloudinary.com/dh81vvqax/image/upload/v1789061543/Gringa_de_Suadero_rjv8gi.jpg',
  },
  {
    id: 'a6',
    nombre: 'Torta al Pastor',
    precio: 5.50,
    categoria: 'alimentos',
    imagen: 'https://res.cloudinary.com/dh81vvqax/image/upload/v1789061547/Torta_al_Pastor_hbnlcz.webp',
  },
  {
    id: 'a7',
    nombre: 'Nachos Supremos',
    precio: 7.00,
    categoria: 'alimentos',
    imagen: 'https://res.cloudinary.com/dh81vvqax/image/upload/v1789061543/Nachos_Supremos_d8khjg.jpg',
  },
  {
    id: 'a8',
    nombre: 'Flautas de Pollo (4 uds)',
    precio: 4.25,
    categoria: 'alimentos',
    imagen: 'https://res.cloudinary.com/dh81vvqax/image/upload/v1789061543/Flautas_de_Pollo_pbidno.jpg',
  },
  {
    id: 'a9',
    nombre: 'Sopes de Chicharrón (2 uds)',
    precio: 3.75,
    categoria: 'alimentos',
    imagen: 'https://res.cloudinary.com/dh81vvqax/image/upload/v1789061545/Sopes_de_Chicharr%C3%B3n_bkmoeq.jpg',
  },
  {
    id: 'a10',
    nombre: 'Volcán de Birria',
    precio: 4.00,
    categoria: 'alimentos',
    imagen: 'https://res.cloudinary.com/dh81vvqax/image/upload/v1789061546/Volc%C3%A1n_de_Birria_jd5951.jpg',
  },

  // bebidas
  {
    id: 'b1',
    nombre: 'Agua de Horchata (500ml)',
    precio: 1.50,
    categoria: 'bebidas',
    imagen: 'https://res.cloudinary.com/dh81vvqax/image/upload/v1789061542/Agua_de_Horchata_hpajln.webp',
  },
  {
    id: 'b2',
    nombre: 'Agua de Jamaica (500ml)',
    precio: 1.50,
    categoria: 'bebidas',
    imagen: 'https://res.cloudinary.com/dh81vvqax/image/upload/v1789061542/Agua_de_Jamaica_k4eq1a.webp',
  },
  {
    id: 'b3',
    nombre: 'Refresco embotellado',
    precio: 1.25,
    categoria: 'bebidas',
    imagen: 'https://res.cloudinary.com/dh81vvqax/image/upload/v1789061545/Refresco_embotellado_athuwm.webp',
  },
  {
    id: 'b4',
    nombre: 'Cerveza Nacional',
    precio: 2.50,
    categoria: 'bebidas',
    imagen: 'https://res.cloudinary.com/dh81vvqax/image/upload/v1789061542/Cerveza_Nacional_exqf0u.jpg',
  },
  {
    id: 'b5',
    nombre: 'Jugos Naturales',
    precio: 2.00,
    categoria: 'bebidas',
    imagen: 'https://res.cloudinary.com/dh81vvqax/image/upload/v1789061543/Jugo_Natural_de_Naranja_wnv6kx.jpg',
  },
];